port: 80
env: "pro"
table-name: "SHORTENURL"
expire: 720h
log:
  level: -1
  time-format: "2006-01-02T15:04:05Z07:00"
  service-name: "tiny-url"
sequencer:
  node-id: 3
  start: "2024-01-01T00:00:00Z"
storage:
  region: "ap-northeast-1"
