// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/0x726f6f6b6965/tiny-url-go/cmd/api"
	"github.com/0x726f6f6b6965/tiny-url-go/internal/config"
	"github.com/0x726f6f6b6965/tiny-url-go/internal/service"
)

// Injectors from wire.go:

func initApplication(ctx context.Context, cfg *config.AppConfig) (*api.ShortenAPI, error) {
	configSequencerConfig := sequencerConfig(cfg)
	sequencer, err := initSequencer(configSequencerConfig)
	if err != nil {
		return nil, err
	}
	storage, err := dynamoDBSet(ctx, cfg)
	if err != nil {
		return nil, err
	}
	shortedURLService := service.NewTinyURLService(cfg, sequencer, storage)
	shortenAPI := api.NewShortenAPI(shortedURLService)
	return shortenAPI, nil
}
